baseURL = 'https://rschmaelzle.github.io/studio/'
languageCode = 'en-us'
title = 'Studio Evergreen'
theme = 'blowfish'

enableRobotsTXT = true

[params]
  colorScheme = "blowfish" 
  defaultBackgroundImage = "background.jpg"
  
  # YOUR NEW EVERGREEN ICON
  favicon = "favicon.svg"

  [params.homepage]
    layout = "hero" 
    showRecent = false 
    
  [params.header]
    layout = "basic"

  [params.list]
    showHero = false
    showSummary = true
    showTableOfContents = false
    showBreadcrumbs = true

[menu]
  # 1. THE LIBRARY (Book Icon is universal)
  [[menu.main]]
    identifier = "library"
    name = "Library"   # Removed "The" for cleaner look
    url = "/library/"
    weight = 10
    pre = "book"       # 'pre' puts the icon BEFORE the text
    params.icon = "book"

  # 2. THE WORKBENCH (Code/Terminal Icon)
  [[menu.main]]
    identifier = "workbench"
    name = "Lab"       # "Lab" is recognized globally
    url = "/workbench/"
    weight = 20
    params.icon = "code-bracket" # A more visual "code" symbol than terminal

  # 3. THE GALLERY (Eye/View Icon)
  [[menu.main]]
    identifier = "immergruen"
    name = "Gallery"   # Universal term
    url = "/immergruen/"
    weight = 30
    params.icon = "eye" # "Eye" implies looking/visuals better than glasses

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true