\baseURL = 'https://rschmaelzle.github.io/studio/'
languageCode = 'en-us'
title = 'Studio Evergreen'
theme = 'blowfish'

enableRobotsTXT = true

[params]
  colorScheme = "blowfish" 
  # USE YOUR LOCAL IMAGE (Locating it in static/background.jpg)
  defaultBackgroundImage = "background.jpg"

  [params.homepage]
    layout = "hero" 
    showRecent = false 
    
  [params.header]
    layout = "basic"

  [params.list]
    showHero = false        # <--- THIS REMOVES THE BANNER ON SUB-PAGES
    showSummary = true
    showTableOfContents = false
    showBreadcrumbs = true

[menu]
  [[menu.main]]
    identifier = "library"
    name = "The Library"
    url = "/library/"
    weight = 10
    params.icon = "book"

  [[menu.main]]
    identifier = "workbench"
    name = "The Workbench"
    url = "/workbench/"
    weight = 20
    params.icon = "terminal"

  [[menu.main]]
    identifier = "immergruen"
    name = "Gallerie ImmergrÃ¼n"
    url = "/immergruen/"
    weight = 30
    params.icon = "glasses"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true