baseURL = 'https://rschmaelzle.github.io/studio/'
languageCode = 'en-us'
title = 'Studio Evergreen'
theme = 'blowfish'

# Keeps this site "Hidden" from Google (The Public-Private Strategy)
enableRobotsTXT = true

[params]
  colorScheme = "blowfish" 
  defaultBackgroundImage = "background.jpg"

  [params.homepage]
    layout = "hero" 
    showRecent = false 
    
  [params.header]
    layout = "basic"
	
  [params.list]
    showHero = true       # Default to showing images
    showSummary = true    # Show the text summary
    showTableOfContents = false
    showBreadcrumbs = true

[menu]
  [[menu.main]]
    identifier = "library"
    name = "The Library"
    url = "/library/"
    weight = 10
    params.icon = "book"

  [[menu.main]]
    identifier = "workbench"
    name = "The Workbench"
    url = "/workbench/"
    weight = 20
    params.icon = "terminal"

  [[menu.main]]
    identifier = "immergruen"
    name = "Gallerie Immergr√ºn"
    url = "/immergruen/"
    weight = 30
    params.icon = "glasses"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true